#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Launch database
  docker_container:
    name: database
    image: jzhang04/tp-devops-database:latest
    pull: true
    networks:
      - name: db-network
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
