- name: Launch front
  docker_container:
    name: front
    image: jzhang04/tp-devops-front:latest
    recreate: true
    pull: true
    networks:
      - name: app-network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python