#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app
- name: Launch app
  docker_container:
    name: app
    image: jzhang04/tp-devops-simple-api:latest
    pull: true
    networks:
      - name: app-network
      - name: db-network
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/{{ db_name }}"
      SPRING_DATASOURCE_USERNAME: "{{ db_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
      DEFAULT_NAME: "{{ default_name | default('World') }}"
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python